http:
  port: ${GATEWAY_PORT}
admin:
  port: 3006
  host: localhost
apiEndpoints: # The endpoints that are being exposed
  animesApi:
    host: localhost
    paths: '/animes/*'
  authApi:
    host: localhost
    paths: '/auth/*'
  friendsApi:
    host: localhost
    paths: '/friends/*'
  meetingsApi:
    host: localhost
    paths: '/meetings/*'
  profileApi:
    host: localhost
    paths: '/profile/*'
serviceEndpoints: # The true endpoints
  animesService:
    url: http://animea-animes:${ANIMES_PORT} #animea-animes is the name of the docker-network
  authService:
    url: http://animea-auth:${AUTH_PORT}
  friendsService:
    url: http://animea-friends:${FRIENDS_PORT}
  meetingsService:
    url: http://animea-meetings:${MEETINGS_PORT}
  profileService:
    url: http://animea-profile:${PROFILE_PORT}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: animes
    apiEndpoints:
      - animesApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: animesService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  - name: auth
    apiEndpoints:
      - authApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  - name: meetings
    apiEndpoints:
      - meetingsApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: meetingsService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  - name: friends
    apiEndpoints:
      - friendsApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: friendsService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  - name: profile
    apiEndpoints:
      - profileApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: profileService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  
