http:
  port: ${PORT}
admin:
  port: 9876
  host: localhost
apiEndpoints: # The endpoints that are being exposed
  animesApi:
    host: '*.herokuapp.com'
    paths: '/animes/*'
  authApi:
    host: '*.herokuapp.com'
    paths: '/auth/*'
  friendsApi:
    host: '*.herokuapp.com'
    paths: '/friends/*'
  meetingsApi:
    host: '*.herokuapp.com'
    paths: '/meetings/*'
  profileApi:
    host: '*.herokuapp.com'
    paths: '/profile/*'
serviceEndpoints: # The true endpoints
  animesService:
    url: https://animea-animes.herokuapp.com
  authService:
    url: https://animea-auth.herokuapp.com
  friendsService:
    url: https://animea-friends.herokuapp.com
  meetingsService:
    url: https://animea-meetings.herokuapp.com
  profileService:
    url: https://animea-profile.herokuapp.com
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: animes
    apiEndpoints:
      - animesApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: animesService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  - name: auth
    apiEndpoints:
      - authApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  - name: meetings
    apiEndpoints:
      - meetingsApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: meetingsService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  - name: friends
    apiEndpoints:
      - friendsApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: friendsService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  - name: profile
    apiEndpoints:
      - profileApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: profileService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true
  