http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints: # The endpoints that are being exposed
  animesApi:
    host: localhost
    paths: '/api/v1/*'
serviceEndpoints: # The true endpoints
  animesService:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - animesApi
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: animesService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true