http:
  port: ${GATEWAY_PORT}
admin:
  port: 9876
  host: localhost
apiEndpoints: # The endpoints that are being exposed
  animesApi:
    host: ${SERVER_IP}
    paths: '/api/v1/animes/*'
serviceEndpoints: # The true endpoints
  animesService:
    url: http://animea-animes:${ANIMES_PORT} #animea-animes is the name of the docker-network
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - animesApi
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: animesService
              changeOrigin: true
              prependPath:  true
              ignorePath:   false
              stripPath:    true